apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Yashwani14/flask.git
    targetRevision: master       # change if your branch is different
    path: helm                   # your chart lives here
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
